# Maintainers file
#
# This file describes the maintainer groups within this project. More detail on project governance
# is available in the GOVERNANCE.md file found in this repository.
#
# It is structured to be consumable by both humans and programs. To extract its contents
# programmatically, use any TOML-compliant parser.
#
# This file was adapted from the github.com/moby/moby project's MAINTAINERS file.

[Org]

  [Org."Core maintainers"]

  # Core maintainers have final say on technical implementation and coding style.
  # They are ultimately responsible for quality in all its forms. When ownership
  # can cleanly be passed to a subsystem, they are responsible for doing so and
  # holding the subsystem maintainers accountable. If ownership is unclear, they
  # are the de facto owners.

    people = [
      "ethanjli",
    ]

  [Org.Curators]

  # The curators help ensure that incoming issues and pull requests are properly
  # triaged and that our various contribution and reviewing processes are respected.
  # With their knowledge of the repository activity, they can also guide contributors
  # to relevant material or discussions.
  #
  # They are neither code nor docs reviewers, so they are never expected to merge.
  # They can, however:
  # - close an issue or pull request when it's an exact duplicate
  # - close an issue or pull request when it's inappropriate or off-topic

    people = [
      "ethanjli",
    ]

  [Org.Alumni]

  # This list contains maintainers that are no longer active on the project. It is
  # thanks to these people that the project has become what it is today. Thank you!

    people = [
      # This nameless person did X, Y, and Z things for this project.
      "",
    ]

[people]

# A reference list of all people associated with the project. All other sections
# should refer to people by their canonical key in this section.

  # ADD YOURSELF HERE IN ALPHABETICAL ORDER

  [people.ethanjli]
  Name = "Ethan Li"
  Email = "lietk12@gmail.com"
  GitHub = "ethanjli"
